---
- name: Clone dotfiles
  become_user: "{{ username }}"
  ansible.builtin.git:
    repo: https://github.com/{{ github_username }}/{{ dotfiles.repo_name }}.git
    dest: /home/{{ username }}/projects/{{ dotfiles.repo_name }}
    clone: yes
    update: yes
  when: dotfiles is defined

- name: Stow files
  become_user: "{{ username }}"
  community.general.make:
    chdir: /home/{{ username }}/projects/{{ dotfiles.repo_name }}
    target: all
  when: dotfiles is defined
