---
- name: Install zsh
  become: true
  ansible.builtin.apt:
    name: zsh
    update_cache: yes

- name: Ensure group "developers" exists
  ansible.builtin.group:
    name: developers
    state: present

- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Create user
  ansible.builtin.user:
    name: "{{ username }}"
    comment: "{{ username }}"
    shell: /usr/bin/zsh
    group: developers

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: yes

- name: Configuring sudoer access
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^{{ username }}'
    line: '{{ username }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Set authorized keys taken from url
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: https://github.com/{{ github_username }}.keys

- name: Copy ssh pub key from local to server
  ansible.builtin.copy:
    src: "{{ ssh_pub_key_file }}"
    dest: "/home/{{ username }}/.ssh/"
    owner: "{{ username }}"
    group: developers
    mode: '600'
  when: ssh_pub_key_file is defined

- name: Copy ssh private key from local to server
  ansible.builtin.copy:
    src: "{{ ssh_priv_key_file }}"
    dest: "/home/{{ username }}/.ssh/"
    owner: "{{ username }}"
    group: developers
    mode: '600'
  when: ssh_priv_key_file is defined

- name: Create projects if it does not exist
  ansible.builtin.file:
    path: /home/{{ username }}/projects
    state: directory
    owner: "{{ username }}"
    group: "developers"
    mode: '0755'
