---
- name: Install financialcpp
  ansible.builtin.shell: GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@github.com:financialcpp/financialcpp.git /home/{{ username }}/projects/financialcpp || true

- name: Install dev
  ansible.builtin.shell: GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@github.com:willhoyle/dev.git /home/{{ username }}/projects/dev || true

