---
- name: Deploy fpp development server
  hosts: fpp
  remote_user: root
  vars_files:
    - variables/users.yaml
  tasks:
    - name: Create user accounts
      include_tasks: roles/user/tasks/main.yaml
      vars:
          username: "{{ item.username }}"
          github_username: "{{ item.github_username }}"
          ssh_pub_key_file: "{{ item.ssh_pub_key_file}}"
          ssh_priv_key_file: "{{ item.ssh_priv_key_file}}"
      loop: "{{ users }}"

- name: Install homebrew
  remote_user: will
  hosts: fpp
  tasks:
    - name: Install homebrew
      include_tasks: 
        file: roles/brew/tasks/main.yaml

- name: Install base global software
  remote_user: will
  hosts: fpp
  tasks:
    - name: Ensure all software are installed and up-to-date
      include_tasks: 
        file: roles/software/tasks/main.yaml

- name: Install user specific software (dotfiles, set paths) 
  hosts: fpp
  remote_user: will
  vars_files:
    - variables/users.yaml
  tasks:
    - name: Add homebrew PATH to profile
      include_tasks: 
        file: roles/brew/tasks/profile.yaml
        apply:
          become_user: "{{ item.username }}"
          become: true
      vars:
        username: "{{ item.username }}"
      loop: "{{ users }}"

    - name: Clone and stow dotfiles
      include_tasks:
        file: roles/dotfiles/tasks/main.yaml
        apply:
          become: true
          become_user: "{{ item.username }}"
          # loads .profile properly because it adds -l flag
          become_method: "community.general.sudosu" 
      vars:
        username: "{{ item.username }}"
        github_username: "{{ item.github_username }}"
        dotfiles: "{{ item.dotfiles }}"
      loop: "{{ users }}"

    - name: Ensure all software are installed and up-to-date
      include_tasks: 
        file: roles/software/tasks/user.yaml
        apply:
          become: true
          become_user: "{{ item.username }}"
          # loads .profile properly because it adds -l flag
          become_method: "community.general.sudosu" 
      vars:
        username: "{{ item.username }}"
      loop: "{{ users }}"

    - name: Install projects
      include_tasks: 
        file: roles/projects/tasks/main.yaml
        apply:
          become: true
          become_user: "{{ item.username }}"
          # loads .profile properly because it adds -l flag
          become_method: "community.general.sudosu" 
      vars:
        username: "{{ item.username }}"
        key_file: "{{ item.ssh_key_file }}"
      loop: "{{ users }}"
