---

- name: Clone dotfiles
  ansible.builtin.git:
    repo: https://github.com/{{ dotfiles.repo_name }}.git
    dest: /home/{{ username }}/projects/dotfiles
    clone: yes
    update: yes
  when: dotfiles is defined

- name: Stow files
  community.general.make:
    chdir: /home/{{ username }}/projects/dotfiles
    target: all
  when: dotfiles is defined

- name: Ensure permissions on .ssh/config are correct
  ansible.builtin.file:
    path: /home/{{ username }}/.ssh/config
    mode: '0600'
